### ISSUE TITLE
Use statix to capture and fix anti-patterns in all the nix files

### ISSUE THREAD

**Issue by ghost** [Arcanyx-org/NiXium#65]
ref: [statix](https://github.com/nerdypepper/statix)
See `statix -h` for a full list of options.
Can be configured with `statix.toml` per project. All lints are enabled by default. To generate a minimal config:

```
statix dump > statix.toml
```

To highlight the anti-patterns in your nix code:

```
statix check
```

It recursively finds nix files and raises lints for the provided directory.

To fix several such occurrences:

```
statix fix
```

**Comment by ghost** [comment]
## Github Actions Workflow

Add the following to your project's `.github/workflows/statix.yml`:

```yaml
name: Lint with statix
on:
  push:
    paths:
      - "**.nix"
  workflow_dispatch:

jobs:
  statix:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: statix
      - uses: jocelynthode/statix-action@master
```

The workflow runs automatically on every push to the repository that includes changes to .nix files.

It can also be triggered manually via the "Workflow dispatch" feature in the GitHub Actions tab of the repository. It provides flexibility to run the formatting process as needed outside of the regular push events.


Possible to apply fixes with `statix fix` and push it with something like:

```yaml
- name: Push changes
  uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: "chore: linting nix code with deadnix"
```

or for PR/MR we could use something like `peter-evans/create-pull-request`.
